---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "etcd"
  name: "etcd-service"
  ownerReferences: []
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  ports:
  - port: 2379
    protocol: "TCP"
    targetPort: 2379
  selector:
    app: "etcd"
  type: "NodePort"
---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  annotations: {}
  finalizers: []
  labels:
    app: "etcd"
  name: "etcd-deployment"
  ownerReferences: []
spec:
  replicas: 1
  template:
    metadata:
      annotations: {}
      finalizers: []
      labels:
        app: "etcd"
      ownerReferences: []
    spec:
      containers:
      - args: []
        command: []
        env:
        - name: "ALLOW_NONE_AUTHENTICATION"
          value: "yes"
        envFrom: []
        image: "bitnami/etcd"
        imagePullPolicy: "IfNotPresent"
        name: "etcd-deployment"
        ports:
        - containerPort: 2379
          protocol: "TCP"
        - containerPort: 2380
          protocol: "TCP"
      hostAliases: []
      imagePullSecrets: []
      initContainers: []
      nodeSelector: {}
      tolerations: []

