# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.990.5
LABEL maintainer="dev@ballerina.io"

COPY books_search_service.balx /home/ballerina 

EXPOSE  9090
CMD ballerina run  books_search_service.balx
